modLoader = "javafml"
loaderVersion = "[47,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_source}"
logoFile="assets/bedrockskins/icon.png"
authors="${mod_authors}"
description="${mod_description}"
credits="${mod_credits}"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version_range}]"
ordering = "NONE"
side = "BOTH"